### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by siordache94** [mvnrc/Unity-Package-Uninstaller#1]
I've been trying to use your plugin but it's broken. The errors are in the screenshot.
Thanks :D 
![image](https://user-images.githubusercontent.com/16574126/31583418-ab8af318-b19b-11e7-93ce-cbc20faa74d7.png)

**Comment by stealthcold** [comment]
@siordache94 , while waiting for a definitive solution from the developer, you can solve this error editing the file "Movinarc\PackageUninstaller\Editor\PUSelection.cs".
Change the ClearWarnings() method:

From: var logEntries = System.Type.GetType("UnityEditorInternal.LogEntries,UnityEditor.dll"); 
To: var logEntries = System.Type.GetType("UnityEditor.LogEntries,UnityEditor.dll");

**Comment by siordache94** [comment]
Woah! finally managed to try it out and it works
thank you very much :D
